server:
  port: 5000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: http://localhost:5001/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth-service
            - JwtAuthFilter
        - id: order-service
          uri: http://localhost:5002/
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - PrefixPath=/order-service
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:5003/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart-service
            - JwtAuthFilter
        - id: product-service
          uri: http://localhost:5004/
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
            - PrefixPath=/product-service
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
